# EHS Electronic Journal - Docker Compose Configuration
# Complete laboratory management system deployment

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ehs_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ehs_electronic_journal}
      POSTGRES_USER: ${POSTGRES_USER:-ehs_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    # Remove exposed ports for security - only internal access needed
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgresql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - ehs_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ehs_user} -d ${POSTGRES_DB:-ehs_electronic_journal}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: ehs_backend
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-ehs_user}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-ehs_electronic_journal}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-false}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ehs_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: ehs_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - ehs_network
    restart: unless-stopped

  # Redis for Session Management (Optional)
  redis:
    image: redis:7-alpine
    container_name: ehs_redis
    # Remove exposed ports for security - only internal access needed
    volumes:
      - redis_data:/data
    networks:
      - ehs_network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  ehs_network:
    driver: bridge